= Documentation
:toc:

=UPDATE
works straight out the box
ENJOY








== Custom Files

[horizontal]
'custom/ads.php'::
Included at the bottom of the claim page, for ads to be shown a ton of times.
'custom/ads_q.php'::
For &lsquo;quality&rsquo; ads &mdash; ads that shouldn&#700;t be shown on the automatic pages.
If an advertiser says that auto-refreshers aren&#700;t allowed, put their ad in this file instead of 'ads.php'.
'custom/claim_options.php'::
Extra form elements to add to the entry form on 'index.php'.
(Can be left empty.)
'custom/claim_options_process.php'::
For options that affect payout amounts. Included by 'faucet.php'.
(Can also be left empty.)
'custom/head.php'::
Included in the &lt;head&gt; tag of every page, for anti-adblock and link:https://www.internetdefenseleague.org[IDL scripts], google analytics, etc.
'custom/iframetraffic.php'::
Put sponsored sites here; it is included in the middle of the claim page.
'custom/navbar.php'::
This file contains the navbar at the top of most of the faucet pages.
You can add and remove links here.

== How to un-ban IP addresses

Open your '.htaccess' file and remove the line `deny from IP`, where *IP* is the IP address to un-ban.
